server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /html/
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*Mapping.xml
  type-aliases-package: com.entity
#showSql 日志级别，打印dao接口的日志
logging:
  level:
    com:
      dao: debug
